### ISSUE TITLE
Incompatible dependency MarkupSafe from Mako

### ISSUE THREAD

**Issue by reloxx13** [Tautulli/Tautulli#1523]
### Describe the Bug

Since today my nightly installation on windows and python 3.9.x isnt starting anymore.

could be related to #1522
Manual start outputs this error:

C:\Python39\pythonw39.exe "S:\Program Files\Tautulli\Tautulli.py"
```
S:\Program Files\Tautulli>C:\Python39\python39.exe "S:\Program Files\Tautulli\Tautulli.py"
Traceback (most recent call last):
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 300, in _install_highlighting
    _install_pygments()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 284, in _install_pygments
    from mako.ext.pygmentplugin import syntax_highlight  # noqa
  File "S:\Program Files\Tautulli\lib\mako\ext\pygmentplugin.py", line 7, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\Program Files\Tautulli\Tautulli.py", line 39, in <module>
    import plexpy
  File "S:\Program Files\Tautulli\plexpy\__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "S:\Program Files\Tautulli\plexpy\activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "S:\Program Files\Tautulli\plexpy\activity_processor.py", line 32, in <module>
    from plexpy import database
  File "S:\Program Files\Tautulli\plexpy\database.py", line 31, in <module>
    from plexpy import helpers
  File "S:\Program Files\Tautulli\plexpy\helpers.py", line 65, in <module>
    from plexpy.api2 import API2
  File "S:\Program Files\Tautulli\plexpy\api2.py", line 61, in <module>
    from plexpy import notification_handler
  File "S:\Program Files\Tautulli\plexpy\notification_handler.py", line 64, in <module>
    from plexpy.newsletter_handler import notify as notify_newsletter
  File "S:\Program Files\Tautulli\plexpy\newsletter_handler.py", line 36, in <module>
    from plexpy import newsletters
  File "S:\Program Files\Tautulli\plexpy\newsletters.py", line 27, in <module>
    from mako.lookup import TemplateLookup
  File "S:\Program Files\Tautulli\lib\mako\lookup.py", line 12, in <module>
    from mako import exceptions
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 305, in <module>
    _install_highlighting()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 302, in _install_highlighting
    _install_fallback()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 290, in _install_fallback
    from mako.filters import html_escape
  File "S:\Program Files\Tautulli\lib\mako\filters.py", line 42, in <module>
    html_escape = markupsafe.escape
AttributeError: module 'markupsafe' has no attribute 'escape'
```

### Tautulli Version

2.7.7 ?

### Git Branch

nightly

### Git Commit Hash

how if its not starting
5d46655507737bc34c09c470b83dd806998dc347

### Platform and Version

win10x64

### Python Version

3.9.6

### Browser and Version

how if its not starting

### Link to Logs

tell me where they r located, i see no log folder

**Comment by TheMeanCanEHdian** [comment]
I suspect this issue is related to the recent dependency updates on nightly.

**Comment by JonnyWong16** [comment]
Resolved.

**Comment by reloxx13** [comment]
now i get 
```
C:\Python39\python39.exe "S:\Program Files\Tautulli\Tautulli.py"
Traceback (most recent call last):
  File "S:\Program Files\Tautulli\Tautulli.py", line 29, in <module>
    import argparse
ImportError: bad magic number in 'argparse': b'\x03\xf3\r\n'
```

Latest git `c9675b2fde62f268eb79dede7c1f5f6298476b6d` and i checked clean state
```
git status
On branch nightly
Your branch is up to date with 'origin/nightly'.

nothing to commit, working tree clean
```


Same on python 310

```
S:\Program Files\Tautulli>C:\Python310\python310.exe.lnk "S:\Program Files\Tautulli\Tautulli.py"
Traceback (most recent call last):
  File "S:\Program Files\Tautulli\Tautulli.py", line 29, in <module>
    import argparse
ImportError: bad magic number in 'argparse': b'\x03\xf3\r\n'
```

**Comment by JonnyWong16** [comment]
That's not a bug. That happens when you try to switch Python versions.

https://www.reddit.com/r/Tautulli/comments/khk5re/tautulli_fails_to_start_after_upgrading_from/gglngsx/

**Comment by reloxx13** [comment]
> 
> 
> That's not a bug. That happens when you try to switch Python versions.
> 
> https://www.reddit.com/r/Tautulli/comments/khk5re/tautulli_fails_to_start_after_upgrading_from/gglngsx/

okay thank you. yeah i switched back to 2.x to keep it running.

**Comment by reloxx13** [comment]
im still getting the same errors as before after cleaning .pyc :S

```
S:\Program Files\Tautulli>git status
On branch nightly
Your branch is up to date with 'origin/nightly'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        contrib/clean_pyc.bat

nothing added to commit but untracked files present (use "git add" to track)

S:\Program Files\Tautulli>c:\Python39\python39.exe "S:\Program Files\Tautulli\Tautulli.py"
Traceback (most recent call last):
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 300, in _install_highlighting
    _install_pygments()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 284, in _install_pygments
    from mako.ext.pygmentplugin import syntax_highlight  # noqa
  File "S:\Program Files\Tautulli\lib\mako\ext\pygmentplugin.py", line 7, in <module>
    from pygments import highlight
ModuleNotFoundError: No module named 'pygments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\Program Files\Tautulli\Tautulli.py", line 39, in <module>
    import plexpy
  File "S:\Program Files\Tautulli\plexpy\__init__.py", line 67, in <module>
    from plexpy import activity_handler
  File "S:\Program Files\Tautulli\plexpy\activity_handler.py", line 37, in <module>
    from plexpy import activity_processor
  File "S:\Program Files\Tautulli\plexpy\activity_processor.py", line 32, in <module>
    from plexpy import database
  File "S:\Program Files\Tautulli\plexpy\database.py", line 31, in <module>
    from plexpy import helpers
  File "S:\Program Files\Tautulli\plexpy\helpers.py", line 65, in <module>
    from plexpy.api2 import API2
  File "S:\Program Files\Tautulli\plexpy\api2.py", line 61, in <module>
    from plexpy import notification_handler
  File "S:\Program Files\Tautulli\plexpy\notification_handler.py", line 64, in <module>
    from plexpy.newsletter_handler import notify as notify_newsletter
  File "S:\Program Files\Tautulli\plexpy\newsletter_handler.py", line 36, in <module>
    from plexpy import newsletters
  File "S:\Program Files\Tautulli\plexpy\newsletters.py", line 27, in <module>
    from mako.lookup import TemplateLookup
  File "S:\Program Files\Tautulli\lib\mako\lookup.py", line 12, in <module>
    from mako import exceptions
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 305, in <module>
    _install_highlighting()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 302, in _install_highlighting
    _install_fallback()
  File "S:\Program Files\Tautulli\lib\mako\exceptions.py", line 290, in _install_fallback
    from mako.filters import html_escape
  File "S:\Program Files\Tautulli\lib\mako\filters.py", line 42, in <module>
    html_escape = markupsafe.escape
AttributeError: module 'markupsafe' has no attribute 'escape'

S:\Program Files\Tautulli>git rev-parse --short HEAD
c9675b2f

S:\Program Files\Tautulli>c:\Python39\python39.exe --version
Python 3.9.6

S:\Program Files\Tautulli>

```

**Comment by JonnyWong16** [comment]
You have global site-packages that conflict with Tautulli (things you installed using `pip install`).

Either uninstall your global packages (`C:\Python39\python39.exe -m pip uninstall MarkupSafe`) or create a separate virtual environment for Tautulli that doesn't copy over any of the global site-packages.

**Comment by reloxx13** [comment]
Naah, git is not removing the markupafe folder in the lib folder
Edit, it had jus the pycache folder in it
Edit2: after deleting the pycache and markupsafe folder it starts up now.

**Comment by JonnyWong16** [comment]
I'm not talking about the _local_ lib folder in Tautulli. I'm talking about your _global_ python libraries (`C:\Python39\Scripts\Lib\site-packages`). Global libraries are shared across your entire system.

**Comment by reloxx13** [comment]
no its not global, i checked all versions and 3.10 is new installed. 2.x does not have markup installed but some others.

```
S:\Program Files\Tautulli>C:\Python39\python39.exe -m pip uninstall MarkupSafe
WARNING: Skipping MarkupSafe as it is not installed.

S:\Program Files\Tautulli>C:\Python39\python39.exe -m pip list
Package    Version
---------- -------
pip        21.3
setuptools 56.0.0
```
```
S:\Program Files\Tautulli>C:\Python27\python.exe -m pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package    Version
---------- ---------
certifi    2020.6.20
chardet    3.0.4
idna       2.10
pip        20.1.1
PlexAPI    4.0.0
requests   2.24.0
setuptools 41.2.0
urllib3    1.25.9
```

**Comment by JonnyWong16** [comment]
> Edit2: after deleting the pycache and markupsafe folder it starts up now.

Why wasn't that cleared when you deleted all the `.pyc` files per my Reddit post above?

I'm also going to try adding the `MarkupSafe` library back in.

**Comment by reloxx13** [comment]
it was the empty leftover `__PYCACHE__` folder (gitignroed) in the markupsafe folder (which was empty besides the pycache folder.
deleting the .pyc files did not remove the pycache folder.
you can maybe set a pycache folder for everything in the project root. i dont know if its possible in tautulli structur, but i know u can set a folder over enviroments.

Edit:
Recovered from trash bin empty folder:
![grafik](https://user-images.githubusercontent.com/14855001/137596707-44f7ad0a-7acc-4b60-9a5f-241841b58a8e.png)
![grafik](https://user-images.githubusercontent.com/14855001/137596733-64a7981b-ed09-4aae-88ec-2138138bc9f1.png)

**Comment by reloxx13** [comment]
This worked to redirect all cache to a single folder in the tautulli folder. u may like to change it in the start bat.
`C:\Python39\python39.exe  -X pycache_prefix=PYCACHE "S:\Program Files\Tautulli\Tautulli.py"`

**Comment by JonnyWong16** [comment]
I'd rather leave the `__pycache__` folders where they are, but add them to the `clean_pyc` script to remove them.

**Comment by reloxx13** [comment]
> 
> 
> I'd rather leave the `__pycache__` folders where they are, but add them to the `clean_pyc` script to remove them.

This will be hard with windows batch. powershell can recursivly remove specific directories. But thats your decision. ill just add the argument to my auto startup script. ill test python 3.10 now and report back in the other issue.
