### ISSUE TITLE
IOError: [Errno 24] Too many open files: '/opt/plexpy/data/interfaces/default/index.html'

### ISSUE THREAD

**Issue by realvz** [Tautulli/Tautulli#340]
After updating this morning, I am getting this error after every 10 or so minutes.
## v1.2.11 (2015-12-06)

**_FIXED VERSION**_ had incorrect version in the report.

Error !

IOError: [Errno 24] Too many open files: '/opt/plexpy/data/interfaces/default/index.html'

lib/mako/util.py, line 343:
lib/mako/template.py, line 395:
lib/mako/template.py, line 321:
lib/mako/lookup.py, line 311:
lib/mako/lookup.py, line 245:
/opt/plexpy/plexpy/webserve.py, line 49:

**Comment by Thr3d** [comment]
Started seeing this as well after updating to version 49669dc7e0f42b19455b60f593f9e1bb6d198280

**Comment by mannibis** [comment]
Same here:

IOError: [Errno 24] Too many open files: '/Applications/PlexPy/PlexPy/data/interfaces/default/index.html'
/Applications/PlexPy/PlexPy/lib/mako/util.py, line 343:
/Applications/PlexPy/PlexPy/lib/mako/template.py, line 395:
/Applications/PlexPy/PlexPy/lib/mako/template.py, line 321:
/Applications/PlexPy/PlexPy/lib/mako/lookup.py, line 311:
/Applications/PlexPy/PlexPy/lib/mako/lookup.py, line 245:
/Applications/PlexPy/PlexPy/plexpy/webserve.py, line 49:

**Comment by drzoidberg33** [comment]
Please update to 1.2.12, should fix this issue.

Sorry about that.

**Comment by mannibis** [comment]
Fixed by doing a manual git pull, then restarting manually as well. With OSX its:

launchctl [load | unload] ~/Library/LaunchAgents/com.drzoidberg33.plexpy.plist

No problem! Stuff happens :) Best app ever

**Comment by drzoidberg33** [comment]
Resolved.

**Comment by Qosmo** [comment]
How do you do a manual update from Freenas?  I tried running the: sudo git clone https://github.com/drzoidberg33/plexpy.git but that is trying to install it again.

**Comment by mannibis** [comment]
"Git pull" should do the trick

**Comment by Qosmo** [comment]
Thanks mannibis!  Was still receiving an error about something already running on port 8181 so I changed the port, and restart it.  Once the page was brought up, I restarted the page again, and input my information again, but it works.
