### ISSUE TITLE
Deleted Users Cant be re-added

### ISSUE THREAD

**Issue by Coolmanchambers** [Tautulli/Tautulli#465]
Recently i Re-added a user that i deleted from Plex and PlexPy a few months ago.  PlexPy will not re-add the user to my user list, but whenever they play something they show up in the activity stream.  I have gone in and manual turned back on history and notifications for the user, and their history is showing up, but they will not appear in the user list at all.

**Comment by JonnyWong16** [comment]
That's as intended.
You can re-enable the user by going to `http://localhost:8181/undelete_user?username=<the_username>`

**Comment by Coolmanchambers** [comment]
Ok i tried that, and i get the {"message": "Re-added user with username <the_username>."} (using their user name from plex), but the user isnt showing back up in the user list after a refresh or a reboot of PlexPy

**Comment by JonnyWong16** [comment]
Try with the user id instead

```
http://localhost:8181/undelete_user?user_id=<the_user_id>
```

You can find the user ids here: https://plex.tv/api/users

**Comment by Coolmanchambers** [comment]
tried that as well and its says unable to add:

[Removed]

http://localhost:8181/undelete_user?user_id=<XXXXX>
{"message": "Unable to re-add user. Input user_id or username not valid."}

And from the previous attempt by user name, it shows it as successful, just not showing up:
http://localhost:8181/undelete_user?username=<XXXXX>
{"message": "Re-added user with username <XXXXX>."}

3-Jan-2016 11:25:19 - INFO    :: CP Server Thread-7 : PlexPy DataFactory :: Re-adding user with username <XXXXX> to database.
23-Jan-2016 11:25:40 - INFO    :: CP Server Thread-3 : Manual user list refresh requested.

**Comment by JonnyWong16** [comment]
Oh don't add the `<` and `>`

**Comment by Coolmanchambers** [comment]
Hahaha, that was it, it was able to add by the UserID then, and they are now showing up in the list, history and notifications again.

Is there a way to see a list of users you have deleted?  Perhaps an enhancement request to see that list if its possible, and when you click on of the user names to opens a window with the URL to re-add the user?

Are you ok if i purge my users data from the strings above? Or do you want me to leave it in?

Thanks again!

**Comment by JonnyWong16** [comment]
There's no way to see a list of delete users without going into the database. I'll improve it in the future, but it's kind of hidden for now.

**Comment by Coolmanchambers** [comment]
Sounds good.  Thankfully this was a one time thing hopefully and not a common occurrence for many users lol.

I appreciate the help. Thanks again

**Comment by JonnyWong16** [comment]
Resolved.

**Comment by theCheek** [comment]
Apologies for reopening this one, but I think I have the same issue.

I removed a user months ago, and just added him back as a plex friend. He is not showing up in PlexPy, so I followed the first advice of using undelete_user?username=<the_username> but he is still not showing up. 

I would like to try the user id method, but I don't know where I can find what his userid is. All i have is his email address. Any help much appreciated!

EDIT: Sorry, I missed that you could find the userid via https://plex.tv/api/users  - however when following that it says error 

> <errors>
> <error>Please sign in.</error>
> </errors>

However I am signed in!

**Comment by JonnyWong16** [comment]
Are you signed into plex.tv?

**Comment by theCheek** [comment]
Yes of course! Signed out and in again on chrome and edge just in case!

**Comment by theCheek** [comment]
Never mind, I was trying it at work and guess something was blocking it like the coorporate firewall. Just retried at home and it was fine. Apologies!

**Comment by justinmvail** [comment]
Hey Jonny, 
I am unable to hit https://plex.tv/api/users no matter what i do.  Is there anyway this URL changed?  I have tried on the computer running the plex server and another on the same network.  

I was able to hit http://localhost:8181/undelete_user?username=1

with ids going up a sizable amount (more users than i have ever had i think).  However, it didn't bring back my user.  Do you have any ideas?

**Comment by JonnyWong16** [comment]
Sign out of plex.tv and sign back in. Or add your token to the end of the url.

```
https://plex.tv/api/users?X-Plex-Token=YOUR_TOKEN_HERE
```

You're also trying to use a user ID with the username url. You should be using `user_id` if you are using the user ID.

```
http://localhost:8181/undelete_user?user_id=XXXXX
```

Or just use the username.

```
http://localhost:8181/undelete_user?username=XXXXXXXXXX
```

**Comment by justinmvail** [comment]
Thanks Jonny!  I have the account added again. You have made an excellent product.  Thanks so much.
