### ISSUE TITLE
PlexPy has become extremely slow over time.

### ISSUE THREAD

**Issue by Unbridle0065** [Tautulli/Tautulli#720]
**Version:**
1.4.1

**Branch:**
Master

**Commit hash:**
c3378e165339a218bf98d0742d2ecfd0485a519a

**Operating system:**
Windows 10

**Python version:**
Python 2.7

**What happened?**
PlexPy has become extremely slow over time.  Each page takes between 10-15 seconds to load.  Possibly because the database of events has grown large over time?

**Comment by drzoidberg33** [comment]
Please use the full template and include the log. You don't say which pages are taking long.

**Comment by Unbridle0065** [comment]
Wasn't sure what logs would be relevant.  It is literally every page.  Every page within PlexPy takes a long time to load.

**Comment by drzoidberg33** [comment]
> Wasn't sure what logs would be relevant.

The plexpy.log file.

**Comment by Unbridle0065** [comment]
[plexpy.log.txt](https://github.com/drzoidberg33/plexpy/files/276629/plexpy.log.txt)

**Comment by erkston** [comment]
I'm think I'm having the same issue.  After a machine or plexpy restart everything loads very quickly and works great, but after some time (hours/days) something seems to happen that causes extremely slow page loads.  This has happened in all versions since the 1.4 update, currently up to date on master branch, Ubuntu Server 14.04, Python 2.7.6.
[plexpylog.txt](https://github.com/drzoidberg33/plexpy/files/287355/plexpylog.txt)

**Comment by Hellowlol** [comment]
Does the same issue happen if you use Basic auth or no auth?

**Comment by erkston** [comment]
Trying with Basic, will report back

**Comment by Unbridle0065** [comment]
> Does the same issue happen if you use Basic auth or no auth?

I don't see any difference when using basic auth.

**Comment by JonnyWong16** [comment]
Are Plex and PlexPy on different machines?

**Comment by Unbridle0065** [comment]
> Are Plex and PlexPy on different machines?

No.  Same machine.

**Comment by erkston** [comment]
Same for me, Plex and PlexPy are on the same machine, and switching to basic auth still has the same issue.

**Comment by JonnyWong16** [comment]
Does removing the database file speed it up?

Shut down PlexPy and move the `plexpy.db` file out of the folder.

**Comment by Hellowlol** [comment]
Try turning off auth so there are no sessions active.

**Comment by Unbridle0065** [comment]
Not able to test this out right now, will give these suggestions a try in the next couple days and report back.

**Comment by nucshuco** [comment]
Same here. Plex and Plexpy are on same system.
Restarting Plexpy fixes the issue temporarily. 
Freenas 9.10

**Comment by JonnyWong16** [comment]
Can you guys also check the CPU/ram usage after leaving PlexPy running?

**Comment by nucshuco** [comment]
That was the first thing I checked. everything was normal.

**Comment by Johannezzz** [comment]
Hello JonnyWong16, can you tell me which info you need to fix this problem? 
I am running on FreeNas 9.10 with the latest updates and reinstalled PlexPy several times now. 
After importing the database (9mb filesize) the page is almost impossible to load. 
After trying several times to login i can acces the page but it goes very slow and when browsing the page i lose connection due to long loading times.

Plex whitout Plexpy is pointless :D i really love it. 

Logfile:
[Plexpy.txt](https://github.com/drzoidberg33/plexpy/files/299272/Plexpy.txt)

Let me now if you need more info. thanks ;)

**Comment by Hellowlol** [comment]
There seems to be some users that experience this issue. The log isn't helpful well atleast I can spot anything. 

So if this was me a would first tried the api and add option to profile that call. I would have selected some call that access the db.

Depending on the result of the api call I would inspect page in firebug or dev tool and and replay all the http/xhr call one by one to see what's slow.

How many people are using your plexpy?
Tried bumping up the threadpool and/or the que?

**Comment by JonnyWong16** [comment]
I'm pretty sure it's not the db file. Id could be slow API calls or might not even be a PlexPy issue and  the problem is on Plex/network side.

I really need more details with as much information as possible. Just saying it is "loading slow" does not help us at all. #641 is an example of a very good issue report. It's like showing up at the doctor and saying "I'm sick, help me."

As a start, this info would be useful:
- Plex server machine, os, version
- PlexPy machine, os, version
- Your networking setup (accessing locally, behind a reverse proxy, remotely)
- Which pages/elements in particular are loading slowly? Are some slower than others?
- Any console messages (press F12 in your browser)
- Have you tried all the suggests in this thread? What were the results?
- What other troubleshooting steps have you tried?
- etc.

This is not an exhaustive list. Add anything else you can think of.

**Comment by Hellowlol** [comment]
I suspect its related to cherrypys sessions.

**Comment by Unbridle0065** [comment]
- Plex server machine, os, version
  Plex and PlexPy running on the same machine - Windows 10
- Your networking setup (accessing locally, behind a reverse proxy, remotely)
  I see no difference when accessing locally, or remotely using duckdns.
- Which pages/elements in particular are loading slowly? Are some slower than others?
  All pages seem to load in the same manner.  The main page elements load very quickly, but the actual content of what i assume is the database take much longer.

Here is an example:  https://imgur.com/CQQY7kt
- Any console messages (press F12 in your browser)
  I don't see any, but I honestly don't know what to look for here.
- Have you tried all the suggests in this thread? What were the results?
  I have tried all suggestions and see no change.
- What other troubleshooting steps have you tried?
  None.  Not sure what to try, but I will try anything else that is suggested.

**Comment by Johannezzz** [comment]
**Plex server machine, os, version:**
- FreeNas 9.10, Plex version 0.9.16.6.1993 installed in a jail.

**PlexPy machine, os, version:**
- FreeNas 9.10, PlexPy version 1.4.5 installed in a jail.

**Your networking setup (accessing locally, behind a reverse proxy, remotely)**
- Locally and remote no proxy

**Which pages/elements in particular are loading slowly? Are some slower than others?**
- Mostly the login page

**Any console messages (press F12 in your browser)**
- Nothing special to see here, should i screenshot or copy any of these? 

**Have you tried all the suggests in this thread? What were the results?**
- Yes. no change. 

**What other troubleshooting steps have you tried?**
- Installed PlexPy 3 times, all became slow. 
- Haven't tried anything else, nothing changed beside PlexPy
- I am running 2 other PlexPy versions, one old one i could not update and i like to keep (v. 1.1.5) its running fast as hell, and a version 1.4 for a friend which also has the same problems but less it seems. 

**Other:**
- mostly the page loads slow and i cant see the login page where to put my username and password. 
- I don't know if it is related to each other but on my pc in chrome i get wrong poster pictures for some tv-shows and movies, when i click on Hannibal it also loads Mash instead of Hannibal. For example for the TV-Show Hannibal it shows me the picture of Mash. I never had this before with any version.
  I don't have this on my phone where i load the page with Firefox. 
- On both phone and pc and external pc's the page loads slow. 
- Strangely it doesn't always load slow, i think, but i am not 100% sure, it loads slower when there is streaming activity. 
- CPU / Ram, don't see anything weird here, all looking fine. 
- Before version 1.4 i did not had these problems. 

If i can support any more information tell me what you need.

**Comment by JonnyWong16** [comment]
> Mostly the login page

So no problems anywhere else?

> Installed PlexPy 3 times, all became slow.

They started off fast, then got slower? Or slow from the beginning?

> I don't know if it is related to each other but on my pc in chrome i get wrong poster pictures for some tv-shows and movies. For example for the TV-Show Hannibal it shows me the picture of Mash. I never had this before with any version. I don't have this on my phone where i load the page with Firefox.

Clear your browser cache and image cache.

> Strangely it doesn't always load slow, i think, but i am not 100% sure, it loads slower when there is streaming activity.

This line is probably the most useful thing mentioned in this entire thread. The homepage loads slow? Or the login page loads slow when there is activity? You're contradicting yourself.

Other things to check:
- Password hashed or not in the config file?
- Clearing all browser cache.
- To confirm, as mentioned above, restarting the computer fixes it temporarily? Restarting PlexPy fixes it temporarily?

@Hellowlol If it is the cherrypy sessions, then disabling authentication or using basic authentication (and maybe clearing browser cache) should fix it?

**Comment by Johannezzz** [comment]
**So no problems anywhere else?**
When i want to access PlexPy it just won't load, and then when it finally loads after automatic retry from my browser or when i keep pressing refresh it loads eventually and then the problems come mostly if i go to settings and back to home screens. 

**Installed PlexPy 3 times, all became slow.
They started off fast, then got slower? Or slow from the beginning?**
The first 2 became slow almost at start, same problem as described above, yes the page loads but after many refreshes. So i assumed something went wrong with the installation and just reinstalled 2 times. 

**I don't know if it is related to each other but on my pc in chrome i get wrong poster pictures for some tv-shows and movies. For example for the TV-Show Hannibal it shows me the picture of Mash. I never had this before with any version. I don't have this on my phone where i load the page with Firefox.
Clear your browser cache and image cache.**
Tried it but problem remains, dont have this one the phone tough.

**Strangely it doesn't always load slow, i think, but i am not 100% sure, it loads slower when there is streaming activity.
This line is probably the most useful thing mentioned in this entire thread. The homepage loads slow? Or the login page loads slow when there is activity? You're contradicting yourself.**
I dont get it how i am contradicting myself. Homepage loads slow after browsing to it from settings, and login page doesn't load at all at times.

Other things to check:

**Password hashed or not in the config file?**
Not hashed

**Clearing all browser cache.**
Did not help.

**Comment by JonnyWong16** [comment]
> I dont get it how i am contradicting myself. Homepage loads slow after browsing to it from settings, and login page doesn't load at all at times.

When you answered this question you didn't mention the homepage or the settings page at all.

> Which pages/elements in particular are loading slowly? Are some slower than others?
> - Mostly the login page

Just to confirm again, you already tried using basic authentication, or disabling authentication all together? Because then it wouldn't use the login page at all.

**Comment by Johannezzz** [comment]
**Just to confirm again, you already tried using basic authentication, or disabling authentication all together? Because then it wouldn't use the login page at all.**
Testing this out again. atm my PlexPy version 1.4.5 loads but i don't have this setting in version 1.4 (version i run for my friend) The problems aren't always there so i have to test this a couple of times.
Updating the 1.4 version now to 1.4.5 to check this one to. 

**Update:**
After i saved to basic authentication it restarts and then does lot load, looking back into the settings it seemed it did not saved. 
Again choose basic auth. and restarted.
Now with basic authentication it doesn't work either on the freshly updated v. 1.4.5
I am not able to load PlexPy at all on my friends PlexPy version 1.4.5

```
http://*******/home Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
2Navigated to data:text/html,chromewebdata
http://*******/home:1 GET http://*******/home net::ERR_CONNECTION_TIMED_OUT
http://*******/home:1 GET http://*******/home net::ERR_CONNECTION_TIMED_OUT
2Navigated to data:text/html,chromewebdata
```

Will get back to it later, have to go to work now.

**Comment by Johannezzz** [comment]
Basic authentication doesn't fix the problem. Cant load PlexPy and switching to settings and back will bring the same problems.

**Comment by JonnyWong16** [comment]
What about disabled authentication? Have you considered that it's a problem with your network instead?

**Comment by Johannezzz** [comment]
I don't have any network problems. Have not tried disabled authentication.

Question, how can i install a previous version to run them both in different jails?  
the command i use to grab Plexpy is:
git clone https://github.com/drzoidberg33/plexpy.git

i would like to try the latest version before v1.4 again.

Thank you.

**Comment by JonnyWong16** [comment]
Can you try with disabled authentication?

You can change to any version using

```
git fetch origin
git checkout origin v1.3.16
```

**Comment by Johannezzz** [comment]
no authentication does not work either. 

thank you for the commands but could you tell me how to use them instead of the command line given? 
git clone https://github.com/drzoidberg33/plexpy.git
git fetch origin
git checkout origin v1.3.16

Would i run it after the original line?

**Comment by JonnyWong16** [comment]
Can you open the browser dev tools again (F12), then go to the network tab, and refresh the PlexPy page. It will look something like this in Chrome (Firefox is similar):

![image](https://cloud.githubusercontent.com/assets/9099342/15920913/bc150334-2dd2-11e6-9c75-a026a07316c1.png)

There should be a column titled "Time" which tells you how long each item takes to load. Find out which item is taking a long time or post the entire output here.

**Comment by Johannezzz** [comment]
No authentication brought another problem: 
After i saved to no authentication the site worked (still loaded slow and a few times not but i could access it eventually), then i loaded it encountered the same slow/non loading problems.
i wanted to go to settings to enable authentication again, settingS or any menu function like logs did not work. I closed my browser removed all history and browser cache and loaded again, now authentication is enabled and my old password does not work. 

A similar problem i had when i updated my friends PMS to version 1.4.5 from 1.4 i tought he changed his password tough (i updated to check if basic auth. would work for him see a few posts back) but yesterday evening he told me he could not access it and did not change his password. 

Now i did a ssh to the PlexPy folder but can't find the settings for the authentication, username and password. 

Can you help me get this reset so i can do what you asked.

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q3

**Comment by Johannezzz** [comment]
thanks could not find the line, did a wrong search

**Comment by Johannezzz** [comment]
I changed 
http_username = "...."   with username and without
http_password = "12345"  with password and without
http_basic_auth = 0   used a 0 and 1 value

I can't access any of the 2 plexpy's anymore no matter whats settings i change in the config.ini file
I checked if there where some writing error to the config file but the settings do change the way i want them.

**Comment by JonnyWong16** [comment]
PlexPy needs to be shut down when editing the config file.

**Comment by Johannezzz** [comment]
ok will try that. thx.

**Comment by Johannezzz** [comment]
Both work again. thx.

Here are the loading times: 
![output](https://cloud.githubusercontent.com/assets/19758540/15921893/0c524e04-2e25-11e6-919e-36498c71e506.jpg)

**Comment by JonnyWong16** [comment]
The ones that are taking long are calls to your Plex server. Can you screenshot some other pages like history or graphs and a movie's page?

**Comment by Johannezzz** [comment]
brb

**Comment by Johannezzz** [comment]
Both PlexPy sites are much faster as usual atm, only had a few times that the main page would not load. 
I tried many times going to settings, browsing true the settings options then back to the main screen. 
Normally going to setting or back to the main screen would result in the page not loading and me needing to refresh a couple of times to get back. 

I had this twice now on the main page, which is visible on the network stats. 
I had it once when going to the user tab, also in the screenshots. 
Maybe it has something to do with only 1 active stream which is even paused atm. 

![output index error](https://cloud.githubusercontent.com/assets/19758540/15922949/bd01cf5e-2e2a-11e6-8442-443330c5feeb.jpg)
![output mp error](https://cloud.githubusercontent.com/assets/19758540/15922953/bd03dac4-2e2a-11e6-9773-dcbd9b9706a1.jpg)
![output graphs](https://cloud.githubusercontent.com/assets/19758540/15922954/bd034078-2e2a-11e6-9e7f-6bd349cac02d.jpg)
![output users wont load](https://cloud.githubusercontent.com/assets/19758540/15922950/bd027f1c-2e2a-11e6-8607-ddbadc4aeb36.jpg)
![output home wont loading](https://cloud.githubusercontent.com/assets/19758540/15922951/bd02cdaa-2e2a-11e6-8b75-a97301829071.jpg)
![output](https://cloud.githubusercontent.com/assets/19758540/15922952/bd02dd72-2e2a-11e6-9ea7-a1e529fd0c3f.jpg)

Sadly it is time for me to go to work. 
Hope the screenshots helped in any way. When i get home i will try to get more active streams and play some more with the page to get some more errors in the network stats.

**Comment by Johannezzz** [comment]
After making my previous post i went back to check settings, this is the outcome: 

![output setting wont loading](https://cloud.githubusercontent.com/assets/19758540/15923193/217a1bf2-2e2c-11e6-814f-d8e3697b0149.jpg)

**Comment by Johannezzz** [comment]
From said settings window back to Home window: 

![output settings back to home](https://cloud.githubusercontent.com/assets/19758540/15923309/d964ed50-2e2c-11e6-8b39-8487d385086f.jpg)

**Comment by JonnyWong16** [comment]
If you click on the ones that say `(failed)` does it say why it failed?

**Comment by erkston** [comment]
I don't know about anyone else, but this issue seems to have gone for me.  Not exactly sure what fixed it, but I had fallen a bit behind in updating plexmediaserver because for some reason it stopped alerting me that an update was available.  Haven't had any problems since, though I think plexpy was also updated in that time.

**Comment by Unbridle0065** [comment]
> I don't know about anyone else, but this issue seems to have gone for me.

No change for me.

**Comment by danhere** [comment]
Not sure if its related but I was also having similar speed issues as @fidju, even in loading pages like settings, things took a long time. I disabled SSL communication with the PMS this morning and found that all the pages, thumbnails, and settings, everything loads extremely quickly.

Ubuntu 16.04 LTS
PMS v1.3.0.3059
PlexPy v1.4.16
Both PlexPy and PMS running in separate Docker instances on same machine

Non-SSL
![screen shot 2016-11-27 at 12 02 39 pm](https://cloud.githubusercontent.com/assets/241920/20649976/b4163fb0-b499-11e6-8767-d3ec70e9dc1c.png)

SSL
![screen shot 2016-11-27 at 12 03 16 pm](https://cloud.githubusercontent.com/assets/241920/20649975/b4138928-b499-11e6-9d11-26d1ffac37a4.png)
