### ISSUE TITLE
Fresh install but no images loaded

### ISSUE THREAD

**Issue by qpeyramale** [Tautulli/Tautulli#727]
**Version:**
1.4.3
**Branch:**
master
**Commit hash:**

**Operating system:**
FreeBSD 10.2 jail
**Python version:**
2.7.11
**What you did?**
Fresh install
**What happened?**
No images
**What you expected?**
Get the images
**How can we reproduce your issue?**

**What are your (relevant) settings?**
Default
The plexpy folder has full access
**Link to logs:**

https://gist.github.com/qpeyramale/04a7957ce9787308b81def3cd59e0b83

Thanks for the help

**Comment by JonnyWong16** [comment]
Did you import a database? Is it all posters or just some? Basically PlexPy cannot find any of your media.

**Comment by qpeyramale** [comment]
Hello ,thanks for the reply.

No I did not import a database, it fetched my library but can't access to the posters, all of them. 
I followed the installation guide for FreeBSD and that's all. All in root, no user.
Should i do something I didn't know?

Thank you

**Comment by JonnyWong16** [comment]
Does the poster show up if you visit one of the pages directly?

```
http://<plex_ip>:32400/library/metadata/11574/thumb/1463088979
http://<plex_ip>:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/11574/thumb/1463088979&width=300&height=450
```

**Comment by qpeyramale** [comment]
I got 401 Unauthorized :/

**Comment by JonnyWong16** [comment]
Sorry, add your token to the end (from the PlexPy settings)

```
http://<plex_ip>:32400/library/metadata/11574/thumb/1463088979?X-Plex-Token=<your_plex_token>
http://<plex_ip>:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/11574/thumb/1463088979&width=300&height=450&X-Plex-Token=<your_plex_token>
```

**Comment by qpeyramale** [comment]
The first link show the image but the second say 401

**Comment by JonnyWong16** [comment]
Double check the URL again? Make sure it's `&X-Plex-Token=<your_plex_token>` not `?X-Plex-Token=<your_plex_token>`.

**Comment by qpeyramale** [comment]
With `&X-Plex-Token=<your_plex_token>` i got a 404

**Comment by qpeyramale** [comment]
i tried `http://<plex_ip>:32400/photo/:/transcode?url=http://<plex_ip>:32400/library/metadata/11574/thumb/1463088979&width=300&height=450&X-Plex-Token=<your_plex_token>` and the image showed up

**Comment by JonnyWong16** [comment]
OK. That helps.

**Comment by JonnyWong16** [comment]
See if it's fixed in v1.4.4.

**Comment by qpeyramale** [comment]
No images but got this in the log that changed:

> Failed to access uri endpoint /photo/:/transcode?url=https%3A%2F%2F92-136-167-198.a8f22ec20951440fbb5d946389b91e4d.plex.direct%3A32400%2Flibrary%2Fmetadata%2F7046%2Fart%2F1463184078&width=1920&height=1080. Status code 404

**Comment by JonnyWong16** [comment]
I'm thinking this might be something with your PMS instead of PlexPy.

**Comment by qpeyramale** [comment]
How can i check that?

FYI: 

> https://<ip>.a8f22ec20951440fbb5d946389b91e4d.plex.direct:32400/library/metadata/2941/thumb/1463992363?X-Plex-Token=xxx

work. 

but

> https://<ip>.a8f22ec20951440fbb5d946389b91e4d.plex.direct:32400/library/metadata/2941/art/1463992363?X-Plex-Token=xxx

say 404

**Comment by JonnyWong16** [comment]
Make sure all your metadata is up to date. Library refresh, empty trash, optimize, etc.

**Comment by mrchops1024** [comment]
I haven't noticed any issues with images, but while looking through the logs for another problem I noticed the log is riddled with this:

> Failed to get image /library/metadata/3240/thumb/1424580273, falling back to poster.
> Traceback (most recent call last): 
>     File "/opt/plexpy/plexpy/webserve.py", line 2974, in pms_image_proxy 
>         raise Exception(u'PMS image request failed') 
> Exception: PMS image request failed
> 
> Failed to access uri endpoint /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F3240%2Fthumb%2F1424580273&width=300&height=450. Status code 404

This is on 1.4.5.

**Comment by qpeyramale** [comment]
@mrchops1024 Have you got this since 1.4.5 or later? 

Thanks

**Comment by mrchops1024** [comment]
I was getting it on 1.4.5, but it seems to have gone away after verifying my server in the settings (which fixed #734).

**Comment by grokdesigns** [comment]
I am currently having this issue with 1.4.5.

```
Failed to get image /library/metadata/2853/art/1464444154, falling back to None.
Traceback (most recent call last): 
    File "/usr/local/share/plexpy/plexpy/webserve.py", line 2974, in pms_image_proxy 
        raise Exception(u'PMS image request failed') 
Exception: PMS image request failed

Failed to access uri endpoint /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F2853%2Fart%2F1464444154&width=1920&height=1080. Status code 404
```

I can access the image through any of these URLs:

```
http://DOMAINNAME:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/2785/art/1464430564&width=1920&height=1080&X-Plex-Token=PLEXTOKEN
http://IPADDRESS:32400/photo/:/transcode?url=http://IPADDRESS:32400/library/metadata/2785/art/1464430564&width=1920&height=1080&X-Plex-Token=PLEXTOKEN
http://IPADDRESS:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/metadata/2785/art/1464430564&width=1920&height=1080&X-Plex-Token=PLEXTOKEN
```

I just migrated to a new Plex server and brought my old PlexPy database over to it. No movies added to Plex since then are showing images, but they appear in the library. Plex and PlexPy are running in separate FreeBSD jails.

**Comment by JonnyWong16** [comment]
Those are two different images.

The decoded url is

```
http://127.0.0.1:32400/library/metadata/2853/art/146444415
```

but you tested

```
http://127.0.0.1:32400/library/metadata/2785/art/1464430564
```

**Comment by grokdesigns** [comment]
@JonnyWong16, sorry about that. I was testing the URLs from one error message and copied another one as an example. The issue occurs for several movies. I just tested the one from my example and have the same results.

**Comment by JonnyWong16** [comment]
Can you test this uri with your plex token in the loopback url as well?

```
/photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F2853%2Fart%2F1464444154%3FX-Plex-Token%3D<PLEX_TOKEN>&width=1920&height=1080&X-Plex-Token=<PLEX_TOKEN>
```

**Comment by grokdesigns** [comment]
@JonnyWong16 I actually figured out what was causing it in my case. All of a sudden, my Apple TV wasn't loading artwork either, so I knew it wasn't PlexPy. On a whim, I used FreeNAS's option to 'disable security' on my Plex jail and everything started working. So now to figure out why it's doing that.

**Comment by fliiiix** [comment]
I guess I have the same problem 

```
Failed to get image /library/metadata/35535/thumb/1466944492, falling back to poster.
```

But if I try 

```
http://<plexip>:32400/library/metadata/35535/thumb/1466944492
```

I get a Image.

**Comment by JonnyWong16** [comment]
Is this still an issue for anyone?

**Comment by fliiiix** [comment]
I just upgraded everything to latest and fixed a problem with my plex server.
Looks like it fixed the problem. And thanks again for fixing #820 :+1:

**Comment by smcpeck** [comment]
Not trying to necrobump, but I'm seeing this exact issue.

Hit the URL manually with my token provided on the queryString shows the image.  But PlexPy is not showing any images whatsoever.

@fliiiix What was the "problem" you fixed with your plex server?
@JonnyWong16 Any thoughts?

**Comment by smcpeck** [comment]
Bah!  I figured out a solution -- running PlexPy under `sudo` fixed my issue.

**Comment by drakonstein** [comment]
I had this problem as well.  The fix for me, and probably for you @smcpeck was to change the owner of my cache folder /opt/plexpy/cache/ to be owned by plexpy:nogroup and to clear the cache using http://plexpy/clear_image_cache . That reset my cache folder and everything started working after that.  Unfortunately, existing missing images are still missing.  This includes things like most watched movies and such.

edit - clearing my browser cache fixed all missing media
